export enum PAGE_TYPE {
  BUILDINGS_LIST = 'BUILDINGS_LIST',
  BUILDING = 'BUILDING',
  BUILDING_ADD = 'BUILDING_ADD',
  BUILDING_EDIT = 'BUILDING_EDIT',
  HARDWARE = 'HARDWARE',
  HARDWARE_ADD = 'HARDWARE_ADD',
  HARDWARE_EDIT = 'HARDWARE_EDIT',
  SERVICE = 'SERVICE',
  SERVICE_ADD = 'SERVICE_ADD',
  SERVICE_EDIT = 'SERVICE_EDIT',
}
