export enum MENU_HEADER {
  EDIT = 'Редактировать',
  DELETE = 'Удалить',
}

/**
 * @description Тип контента при создании хедера объекта
 */
export enum TYPE_CONTENTS {
  LIST_OBJECTS = 'LIST_OBJECTS',
  EDIT_OBJECTS = 'EDIT_OBJECTS',
  EDIT_OBJECTS_TAB_SERVICES = 'EDIT_OBJECTS_TAB_SERVICES',
  EDIT_OBJECTS_TAB_DOCUMENTATIONS = 'EDIT_OBJECTS_TAB_DOCUMENTATIONS',
  EDIT_OBJECTS_TAB_HARDWARES = 'EDIT_OBJECTS_TAB_HARDWARES',
}
